In [10]:
import pandas as pd
from sklearn.utils import resample
df = pd.read_excel(r"C:\Users\gargi\Downloads\Logit model data 1.xlsx")
df

,Name,Gender,Code,2001-2005,2005-2010,2010-2015,2015-2017,2017-2019,2019-present,WEAT_score,...,Political_party,LP,CP,Independent,LD,SNP,Others,Num_words,Average Views Daily,Average Views Monthly
0,Ã“rfhlaith Begley,Female,1,0,0,0,0,1,1,0.008272,...,Sinn FÃ©in,0,0,0,0,0,1,1095,1.000000,1.000000
1,Aaron Bell (politician),Male,0,0,0,0,0,0,1,0.027587,...,Conservative,0,1,0,0,0,1,1159,75.751288,2286.577778
2,Abena Oppong-Asare,Female,1,0,0,0,0,0,1,0.037326,...,Labour,1,0,0,0,0,1,1078,71.640177,2162.777778
3,Adam Afriyie,Male,0,0,1,1,1,1,1,-0.018817,...,Conservative,0,1,0,0,0,1,2561,98.235050,2990.768421
4,Adam Holloway,Male,0,0,1,1,1,1,1,-0.001819,...,Conservative,0,1,0,0,0,1,3212,53.976149,1643.210526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121,Willie Rennie,Male,0,0,1,0,0,0,0,0.061518,...,Scottish Liberal Democrats,1,0,0,0,0,0,2734,93.174559,2836.936842
1122,Win Griffiths,Male,0,1,0,0,0,0,0,0.116669,...,Labour,1,0,0,0,0,0,386,6.753659,203.978947
1123,Yvette Cooper,Female,1,1,1,1,1,1,1,0.040978,...,Labour,1,0,0,0,0,1,5272,579.126512,17633.284211
1124,Yvonne Fovargue,Female,1,0,0,1,1,1,1,0.064535,...,Labour,1,0,0,0,0,1,660,27.899067,849.421053
1125,Zac Goldsmith,Male,0,0,0,1,1,1,0,0.004020,...,Conservative,0,0,0,0,0,1,9492,893.085033,27191.421053

In [4]:
import wikipedia
names = df['Name']
i = 0
for name in names:
    content = wikipedia.page(name, auto_suggest=False).content
    df.at[i,'Content'] = content
    i= i+1

In [5]:
df

,Name,Gender,Content
0,Anne Campbell (politician),Female,Anne Campbell (born 6 April 1940) is an Englis...
1,Mark Garnier,Male,Mark Robert Timothy Garnier (born 26 February...
2,Darren Henry,Male,Darren George Henry (born 4 August 1968) is a ...
3,Michael Gove,Male,Michael Andrew Gove (; born Graeme Andrew Loga...
4,Peter Grant (politician),Male,Peter Grant (born 12 October 1960) is a Scotti...
...,...,...,...
1122,Paul Burstow,Male,Paul Kenneth Burstow (born 13 May 1962) is a B...
1123,David Atkinson (politician),Male,David Anthony Atkinson (24 March 1940 – 23 Jan...
1124,Thangam Debbonaire,Female,Thangam Elizabeth Rachel Debbonaire (née Singh...
1125,Tom Hunt (politician),Male,Thomas Patrick Hunt (born 31 August 1988) is a...
1126,Conor Burns,Male,Sir Conor Burns (born 24 September 1972) is a ...

In [11]:
df_male = df[df['Gender'] == 'Male']
df_female = df[df['Gender'] == 'Female']

In [7]:
df.to_csv('upsampled final.csv')

In [12]:
df_female_upsampled = resample(df_female, 
                               replace=True,
                               n_samples=len(df_male), 
                               random_state=123)

In [13]:
df_upsampled = pd.concat([df_male, df_female_upsampled])

In [14]:
print(df_upsampled['Gender'].value_counts())

Gender
Male      800
Female    800
Name: count, dtype: int64

In [15]:
df_upsampled

,Name,Gender,Code,2001-2005,2005-2010,2010-2015,2015-2017,2017-2019,2019-present,WEAT_score,...,Political_party,LP,CP,Independent,LD,SNP,Others,Num_words,Average Views Daily,Average Views Monthly
1,Aaron Bell (politician),Male,0,0,0,0,0,0,1,0.027587,...,Conservative,0,1,0,0,0,1,1159,75.751288,2286.577778
3,Adam Afriyie,Male,0,0,1,1,1,1,1,-0.018817,...,Conservative,0,1,0,0,0,1,2561,98.235050,2990.768421
4,Adam Holloway,Male,0,0,1,1,1,1,1,-0.001819,...,Conservative,0,1,0,0,0,1,3212,53.976149,1643.210526
5,Adam Ingram (Labour politician),Male,0,1,1,0,0,0,0,-0.012465,...,Labour,1,0,0,0,0,1,962,15.921535,484.621053
6,Adam Price,Male,0,1,1,0,0,0,0,0.042088,...,Plaid Cymru,1,0,1,0,0,1,4065,138.882821,4228.694737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100,Tracy Brabin,Female,1,0,0,0,1,1,1,-0.017916,...,Labour and Co-operative,0,0,0,0,0,1,2489,529.896301,16134.357895
84,Annabelle Ewing,Female,1,1,0,0,0,0,0,0.039432,...,Scottish National Party,0,0,0,0,1,0,1698,34.870722,1061.484211
408,Harriet Harman,Female,1,1,1,1,1,1,1,-0.008927,...,Labour,1,1,1,0,0,0,9219,712.754926,21701.389474
812,Nickie Aiken,Female,1,0,0,0,0,0,1,0.061416,...,Conservative,0,1,0,0,0,0,1138,129.244297,3900.888889
469,Jackie Lawrence (politician),Female,1,1,0,0,0,0,0,0.030969,...,Labour,1,0,0,0,0,0,470,8.653259,262.589474

In [16]:
df_upsampled.to_excel('df_upsampled.xlsx')